---

service: oauth-token-api

provider:
  name: aws
  runtime: nodejs4.3
  region: us-east-2
  profile: festify
  memorySize: 128

package:
  include:
    - lib/**

functions:
  exchangeCode:
    handler: spotifyTokenService.exchangeCode
    events:
      - http:
          path: exchange
          method: post
          cors: true
  refreshToken:
    handler: spotifyTokenService.refreshToken
    events:
      - http:
          path: refresh
          method: post
          cors: true
